### ISSUE TITLE
The latest Roots update causes other mods to crash when used with it

### ISSUE THREAD

**Issue by gregest** [EpicSquid/Roots#374] opened 2020-01-20 22:05 UTC
### General Information

**Describe the bug:**
Since the latest roots update, weird Rendering Entity crashes started to happen, first it happened with quark glass frame so I disabled that then it started to happen with thaumcraft and at that point I guessed that it was the latest roots update and when I went back one version, the issue was fixed

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: mysticallib-1.12.2-1.5.0
- Roots: Roots-1.12.2-3.0.22
- MysticalWorld: mysticalworld-1.12.2-1.7.0

**Other Versions:**
- Conflicting mod (if regarding mod integration): Quark and thaumcraft and might be others but I didnt go that far
- Forge: forge-14.23.5.2847
- Minecraft: 1.12

**Crash Report (if available):**
https://paste.dimdev.org/pujuhukuhe.mccrash

**Comment by noobanidus** [comment] 2020-01-20 22:58
That's strange, and I understand what's happening but I'm confused as to why it's happening. I'll try to get 3.0.23 out ASAP.

**Comment by ErnestoPeroPezzi** [comment] 2020-01-20 23:45
Hello, I am also having this issue, did not realize Roots was the cause. I have already reported on Silents gems (as that is the mod it had the problem with. Point of note, after the crash, when logging back in, keeping the mouse still does the thing where all the blocks visually dissapear and all that is visible are entities in the minecraft fog

https://github.com/SilentChaos512/SilentGems/issues/439

**Comment by noobanidus** [comment] 2020-01-20 23:48
Yeah, I understand why it's happening: I'm doing "lazy initialisation", where the list of acceptable mobs isn't called until the very first time the list is asked for. But it turns out that it's happening at the same time as *another* initialisation, and because I'm then iterating over the list, it's causing the concurrent modification error.

**Comment by noobanidus** [comment] 2020-01-21 01:42
I've just pushed a fix to CurseForge which will hopefully be approved shortly. Could you try it out and let me know if it fixes your problems? I believe I've addressed it -- my only concern would... well, honestly, I can't think of anything that m ight go wrong.

**Comment by ErnestoPeroPezzi** [comment] 2020-01-21 15:28
Been playing for about 3 hours and all seems well. Last time, game crashed within 30-40 mins after updating and playing. I tried to do the same things as I was doing when it crashed, seems like no issues so far. Good stuff <3

**Comment by gregest** [comment] 2020-01-21 15:33
can confirm that it's all good now, the game isn't crashing anymore

**Comment by noobanidus** [comment] 2020-01-21 23:18
Excellent, I'm glad that fixed it because it was a bit difficult for me to actually properly test it. I'll consider it closed then -- if anyone else has any issues using 3.0.23, please comment with your crash report and I'll reopen this issue.

**Closed as completed by noobanidus** 2020-01-21 23:18 UTC
