### ISSUE TITLE
Roots sending lots of packets

### ISSUE THREAD

**Issue by Darkere** [EpicSquid/Roots#100] opened 2019-04-14 13:04 UTC
![image](https://user-images.githubusercontent.com/4283717/56092997-db285d00-5ec3-11e9-96e9-c882bd5cd8e1.png)

This is the packet count for a fresh world. And while they do not seem to cause any performance problems not sending unnecessary data would be nice.

**Comment by EpicSquid** [comment] 2019-04-14 21:26
Yeah it's insane. This issue is fixed in roots 3

**Comment by duely** [comment] 2019-04-14 23:36
I haven't specifically looked into the code for whichever version you're using (Roots or Roots Classic or Roots 2, I get confused with everything), but part of the issue is update packets being sent unnecessarily to people who don't really need to know that something got updated.

In Roots 3, there was a significant issue with player capabilities for effects being transmitted to everyone on every dimension every tick -- but that's possibly a bug that was introduced during Roots 3. I've resolved this issue, as well as changing all instances where packets were being sent to all players in all dimensions into simply those people who are tracking the relevant location.

**Comment by Darkere** [comment] 2019-04-15 13:25
Ohhhhh.... That's why I couldn't find the problematic code. It's already fixed in the master branch...

In the roots 2 branch Eventmanger 
`PacketHandler.INSTANCE.sendToAll(new MessageLightDrifterFX(event.getEntity().posX,event.getEntity().posY+1.0f,event.getEntity().posZ));`
should only send to people tracking. Entirely possible that there are more instances where this happens but is hard to find through github.

**Comment by duely** [comment] 2019-04-15 23:30
Yeah, there were around 57 occurrences in the main code base that I fixed. I'll try to backport them to Roots 2, to be honest, because it shouldn't be too hard and an update will help people running older packs.

**Closed** 2019-07-02 04:06 UTC
Labels: roots 2, wontfix
