### ISSUE TITLE
Automating Toasted Seeds

### ISSUE THREAD

**Issue by faeldray** [EpicSquid/Roots#402] opened 2020-03-02 17:56 UTC
### General Information

**Describe the bug:**
Attempting to automate toasted seeds on the pyre returns the first batch of 5 seeds, but all other batches just disappear.

**To Reproduce:**

1. Set up pyre with chest underneath.
2. Put seeds in chest.
3. Light pyre with flint and steel.

**Expected behavior:**
All of the seeds are cooked and dropped in the ground, not just the first batch.

***

### Environment Versions
I use a small custom test pack to diagnose issues like this, it includes:
- JourneyMap: 5.7.0
- JEI: 4.15.0.291
- Nature's Compass: 1.8.3
- TellMe: 0.70
- The One Probe: 1.4.28

**Mystic Mods Versions**

- MysticalLib: 1.6.0
- Mystical World: 1.7.1
- Roots: 3.0.25
- Patchouli: 1.0-20

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): Custom

***

### Logging Information
**Latest Log (if necessary):**
https://pastebin.com/5ukyF8Q9

**Comment by majijn** [comment] 2020-03-02 20:26
dupe of #382

**Comment by noobanidus** [comment] 2020-03-03 00:01
And fixed in the 3.1 branch! Hopefully.

**Closed as completed by noobanidus** 2020-03-03 00:01 UTC
Labels: bug
