### ISSUE TITLE
Unending Bowl filling tanks right after right-click, making singularities in AE worthless

### ISSUE THREAD

**Issue by ChromaPIE** [EpicSquid/Roots#370] opened 2020-01-10 16:05 UTC
### General Information

**Describe the bug:**

This might be a FEATURE, but it truly breaks the balance from the perspective of a Modpacker. We have Actually Addition, which provides the fluid laser relay which can transfer fluid immediately, and we have Blood Tank Tier 16, which can contain 524288000 mB of any available fluid. When right click those tanks, tested ones in Mekanism, Blood Magic, Thermal Expansion, Embers Rekindled and Extra Cells 2, the Bowl will fill it to full immediately. But what is weird is that when testing this to the drums in Extra Utilities 2, the Bowl will just give 1000mB to the drum. The feature breaks the balance as when cooperate with the Fluid Laser Relay and the Matter Condenser, it makes the Singularity worthless. And if other Modpacks has something which requires a huge amount of Water or something else related to water to operate, it will be a disaster to the balance.

**To Reproduce:**

Described above.

**Expected behavior:**

Give 1000mB (or a little more is okay) to water containers per right-click.
***

### Environment Versions

3.0.13

**Mystic Mods Versions**

- MysticalLib: 1.3.7

**Other Versions:**
- Conflicting mod (if regarding mod integration): null
- Other mods you think could cause issues: null
- Forge: 2847
- Minecraft: 1.12.2
- Modpack (if available): EnigTech 2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by GreyMario** [comment] 2020-01-10 21:21
As far as Extra Utilities 2 drums go, those things do _not_ play by the rules and actually argue with a lot of modded fluid-holding items. I just wanted to let you know that.

A config option for the bowl sounds like a reasonable suggestion on this front.

**Comment by noobanidus** [comment] 2020-01-10 21:50
~~I'll have to look into this but if you are so concerned about the item there is always the possibility of using CraftTweaker to remove the recipe from the game.~~

~~Part of the issue is that some mods enforce their own limits on how much fluid can be transferred at a time (like XU2), while others rely on on the input/output conduits to determine how much fluid can be transferred.  If I were to artificially limit to 1000mb that would prevent conduits that transfer more than 1000mb at a time from transferring more than 1000mb.~~

~~Honestly, I'm more likely to add an option to *disable* the ItemStack fluid capability than one to actually limit the fluid input.~~

~~If you are also concerned about infinite water sources, you should check out Cooking for Blockheads' sink as another potentially problematic area.~~

~~>  And **if** other Modpacks has something which requires a huge amount of Water or something else related to water to operate, it will be a disaster to the balance.~~

~~Emphasis mine. "If". Can you actually identify any areas where this is actually problematic, or are you just expressing concern the possibility that it might be problematic?~~

EDIT: So, rethinking this after re-reading:

More to the point, can you clarify or quantify the interaction that is actually problematic? 

a) What does the fluid laser relay do? If it doesn't have a built-in cap on transfer, that would be something to discuss with Actually Additions as the Cooking for Blockheads infinite water source, along with the EvilCraft(?) may also be affected.
b) If it is a problematic interaction with the Singularities and the Matter Condenser, is there no option to disable the Matter Condenser from accepting water?
c) How exactly do you want me to change the functionality of the unending bowl? 

Do you want me to:
a) limit the amount of fluid it will output per side per tick to a configurable value?
b) add configuration to disable the right-click interaction with tanks?
b) add configuration to disable the itemstack capability that allows you to use it as a portable infinite water supply?

Your request is:

> Give 1000mB (or a little more is okay) to water containers per right-click.

But what about when you attach the fluid relay directly to the unending bowl? (which should be possible, as it has all of the proper capabilities set up). In this instance, per-right-click is irrelevant as it's directly interfacing with the fluid source.

Honestly, it feels like the issues here are:

a) the fluid laser relay seems to transfer an infinite amount of fluid
b) the matter condenser accepts water as a valid input without regulating how much water can be inserted into it per tick

Both of these issues are the actual cause: if these things functioned differently (especially if the Matter Condenser limited the amount of fluid it accepted per tick), it wouldn't matter how quickly you transferred or how much water you transferred out.

There is no precedent for tanks limiting the amount that can be drained from them or filled to them per tick, as demonstrated by the fact that all of the tanks (except the Extra Utilities 2 tank) would fill completely with right-click. 

If I was to limit it to a static or configurable amount, it would become exactly like the Extra Utilities 2 tank and any fluid conduit or system that moves more than 1000mb per tick would be basically a useless upgrade.

Honestly, at this point, I would [recommend using CraftTweaker to simply remove the Unending Bowl recipe](https://docs.blamejared.com/1.12/en/#Mods/Roots_3/fey/) and potentially modify the Sure-Footed Stone recipe as well, as just a simple change to the "right-click amount" isn't going to resolve your problem.

**Comment by noobanidus** [comment] 2020-01-20 04:16
Just to clarify @ChromaPIE I am waiting on your response before I do anything with this, as I'm not actually sure what you want me to do and why.

**Comment by noobanidus** [comment] 2020-02-16 09:21
Okay, so, there hasn't been any response in five weeks, so I'm closing this as "I have no idea what you want me to do".

**Closed as completed by noobanidus** 2020-02-16 09:21 UTC
