### ISSUE TITLE
[BUG] Cursor crash in library

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#800] opened 2023-04-26 09:09 UTC
**To Reproduce:**
1. Just open gui and move cursor
2. Crash
~ ~ ~
Log:
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.8.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.3.3_Forge_1.12.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.29.5_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/26/23 11:59 AM
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at epicsquid.roots.world.data.SpellLibraryData.asList(SpellLibraryData.java:146)
	at epicsquid.roots.world.data.SpellLibraryData.get(SpellLibraryData.java:157)
	at epicsquid.roots.container.slots.SlotLibraryInfo.func_75211_c(SlotLibraryInfo.java:68)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:202)
	at epicsquid.roots.client.gui.GuiLibrary.func_146977_a(GuiLibrary.java:208)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at epicsquid.roots.client.gui.GuiLibrary.func_73863_a(GuiLibrary.java:63)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at epicsquid.roots.world.data.SpellLibraryData.asList(SpellLibraryData.java:146)
	at epicsquid.roots.world.data.SpellLibraryData.get(SpellLibraryData.java:157)
	at epicsquid.roots.container.slots.SlotLibraryInfo.func_75211_c(SlotLibraryInfo.java:68)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:202)
	at epicsquid.roots.client.gui.GuiLibrary.func_146977_a(GuiLibrary.java:208)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at epicsquid.roots.client.gui.GuiLibrary.func_73863_a(GuiLibrary.java:63)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: epicsquid.roots.client.gui.GuiLibrary
	Mouse location: Scaled: (303, 171). Absolute: (909, 510)
	Screen size: Scaled: (608, 342). Absolute: (1824, 1026). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DinarNaMamky'/71, l='MpServer', x=-219.18, y=29.00, z=458.70]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,256), Chunk: (at 4,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 278551 game time, 459337 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
	Forced entities: 141 total; [EntityRaven['Raven'/256, l='MpServer', x=-293.50, y=45.00, z=459.84], EntityZombie['Zombie'/35840, l='MpServer', x=-173.50, y=22.00, z=471.50], EntityRaven['Raven'/257, l='MpServer', x=-298.45, y=46.00, z=452.41], EntityZombie['Zombie'/35842, l='MpServer', x=-172.50, y=22.00, z=471.50], EntityCreeper['Creeper'/35843, l='MpServer', x=-165.50, y=22.00, z=469.50], EntityZombie['Zombie'/35844, l='MpServer', x=-291.50, y=44.00, z=398.50], EntityBoulderer['Bouldering Zombie'/34827, l='MpServer', x=-217.50, y=31.00, z=398.50], EntityItem['item.item.reeds'/35346, l='MpServer', x=-225.50, y=71.00, z=522.50], EntityZombie['Zombie'/35352, l='MpServer', x=-223.50, y=18.00, z=421.50], EntityItem['item.item.egg'/32793, l='MpServer', x=-225.38, y=72.00, z=438.08], EntitySkeleton['Skeleton'/35358, l='MpServer', x=-245.38, y=52.00, z=438.77], EntityZombie['Zombie'/35103, l='MpServer', x=-239.50, y=20.00, z=475.50], EntityEnderman['Enderman'/35361, l='MpServer', x=-235.50, y=52.00, z=432.50], EntityCreeper['Creeper'/35884, l='MpServer', x=-294.47, y=50.00, z=444.79], EntitySkeleton['Skeleton'/35885, l='MpServer', x=-283.50, y=50.00, z=451.50], EntitySheep['Sheep'/302, l='MpServer', x=-181.12, y=72.00, z=403.74], EntityCreeper['Creeper'/35886, l='MpServer', x=-289.70, y=43.00, z=408.48], EntityPig['Pig'/303, l='MpServer', x=-188.97, y=69.00, z=415.55], EntitySpider['Spider'/35887, l='MpServer', x=-288.79, y=44.00, z=403.82], EntitySheep['Sheep'/304, l='MpServer', x=-180.58, y=72.00, z=393.77], EntityBonepile['Bonepile'/35888, l='MpServer', x=-204.50, y=24.00, z=424.50], EntityEnderman['Enderman'/35889, l='MpServer', x=-190.44, y=23.00, z=500.50], EntityEnderman['Enderman'/35890, l='MpServer', x=-188.50, y=23.00, z=504.50], EntityPig['Pig'/312, l='MpServer', x=-189.28, y=68.00, z=428.46], EntityBat['Bat'/35640, l='MpServer', x=-215.53, y=44.10, z=448.57], EntityBat['Bat'/35641, l='MpServer', x=-228.71, y=33.67, z=454.76], EntityPig['Pig'/313, l='MpServer', x=-196.51, y=67.00, z=411.75], EntityBoulderer['Bouldering Zombie'/9533, l='MpServer', x=-220.30, y=32.64, z=451.45], EntityBat['Bat'/35645, l='MpServer', x=-290.42, y=28.99, z=529.19], EntityChicken['Chicken'/320, l='MpServer', x=-237.11, y=72.00, z=453.45], EntityChicken['Chicken'/321, l='MpServer', x=-223.50, y=68.00, z=446.85], EntityRaven['Raven'/325, l='MpServer', x=-210.96, y=44.00, z=445.58], EntityPig['Pig'/326, l='MpServer', x=-196.05, y=66.00, z=422.45], EntityPig['Pig'/327, l='MpServer', x=-193.24, y=66.00, z=425.49], EntitySheep['Sheep'/331, l='MpServer', x=-200.77, y=67.00, z=395.55], EntityCreeper['Creeper'/34896, l='MpServer', x=-164.50, y=54.00, z=414.50], EntityPig['Pig'/81, l='MpServer', x=-284.61, y=69.00, z=517.71], EntityPig['Pig'/82, l='MpServer', x=-285.55, y=69.00, z=517.36], EntityPig['Pig'/83, l='MpServer', x=-272.26, y=68.00, z=522.27], EntityItem['item.item.egg'/11348, l='MpServer', x=-224.09, y=67.00, z=453.82], EntitySheep['Sheep'/84, l='MpServer', x=-281.78, y=68.00, z=516.48], EntitySpider['Spider'/34900, l='MpServer', x=-283.50, y=36.00, z=405.50], EntityDeer['Deer'/85, l='MpServer', x=-278.14, y=69.00, z=514.92], EntityPig['Pig'/86, l='MpServer', x=-267.50, y=70.00, z=506.62], EntitySheep['Sheep'/347, l='MpServer', x=-171.81, y=70.00, z=468.26], EntitySheep['Sheep'/91, l='MpServer', x=-293.73, y=70.00, z=518.45], EntityPig['Pig'/348, l='MpServer', x=-150.39, y=67.00, z=456.27], EntityPig['Pig'/92, l='MpServer', x=-285.41, y=70.00, z=510.68], EntitySheep['Sheep'/349, l='MpServer', x=-144.50, y=67.00, z=447.80], EntityChicken['Chicken'/94, l='MpServer', x=-258.62, y=62.73, z=482.88], EntitySheep['Sheep'/350, l='MpServer', x=-149.26, y=67.00, z=449.20], EntityZombie['Zombie'/35678, l='MpServer', x=-197.19, y=27.00, z=458.51], EntityChicken['Chicken'/95, l='MpServer', x=-255.49, y=65.00, z=468.86], EntityPig['Pig'/352, l='MpServer', x=-148.23, y=67.00, z=445.50], EntityBat['Bat'/35936, l='MpServer', x=-149.64, y=35.43, z=414.28], EntityChicken['Chicken'/97, l='MpServer', x=-253.79, y=65.00, z=467.51], EntityChicken['Chicken'/99, l='MpServer', x=-251.79, y=66.00, z=469.50], EntityRaven['Raven'/356, l='MpServer', x=-167.50, y=15.00, z=455.50], EntityRaven['Raven'/357, l='MpServer', x=-169.53, y=47.00, z=451.89], EntityPig['Pig'/358, l='MpServer', x=-169.28, y=71.00, z=461.50], EntityPig['Pig'/359, l='MpServer', x=-171.81, y=68.00, z=452.34], EntityCreeper['Creeper'/35687, l='MpServer', x=-240.50, y=52.00, z=395.50], EntitySheep['Sheep'/106, l='MpServer', x=-296.47, y=71.00, z=505.47], EntityRaven['Raven'/363, l='MpServer', x=-169.25, y=30.00, z=432.25], EntitySheep['Sheep'/107, l='MpServer', x=-293.49, y=71.00, z=503.73], EntitySheep['Sheep'/365, l='MpServer', x=-174.30, y=71.00, z=406.82], EntityItem['item.item.egg'/35693, l='MpServer', x=-261.57, y=67.00, z=443.88], EntityPig['Pig'/366, l='MpServer', x=-171.31, y=71.00, z=406.79], EntityChicken['Chicken'/111, l='MpServer', x=-250.49, y=67.00, z=459.85], EntityChicken['Chicken'/112, l='MpServer', x=-226.32, y=72.00, z=438.49], EntitySheep['Sheep'/369, l='MpServer', x=-150.35, y=67.00, z=515.75], EntitySheep['Sheep'/370, l='MpServer', x=-155.52, y=68.00, z=525.27], EntityChicken['Chicken'/114, l='MpServer', x=-233.31, y=72.00, z=445.91], EntityItem['item.item.egg'/35186, l='MpServer', x=-250.95, y=67.00, z=460.66], EntityChicken['Chicken'/115, l='MpServer', x=-261.49, y=67.00, z=443.38], EntityItem['item.item.egg'/35187, l='MpServer', x=-232.36, y=72.00, z=446.04], EntityChicken['Chicken'/116, l='MpServer', x=-256.58, y=68.00, z=446.88], EntityAncientGolem['Ancient Golem'/117, l='MpServer', x=-239.80, y=24.00, z=413.49], EntityChicken['Chicken'/122, l='MpServer', x=-244.81, y=73.00, z=443.42], EntityPig['Pig'/124, l='MpServer', x=-246.41, y=72.00, z=534.28], EntityBat['Bat'/35965, l='MpServer', x=-251.82, y=45.79, z=395.66], EntityItem['item.item.egg'/35203, l='MpServer', x=-258.53, y=62.00, z=482.71], EntityDeer['Deer'/138, l='MpServer', x=-190.04, y=70.00, z=459.88], EntitySpider['Spider'/35978, l='MpServer', x=-190.50, y=54.00, z=401.50], EntityPlayerSP['DinarNaMamky'/71, l='MpServer', x=-219.18, y=29.00, z=458.70], EntityPig['Pig'/139, l='MpServer', x=-181.78, y=68.00, z=474.78], EntitySpider['Spider'/35979, l='MpServer', x=-193.50, y=54.00, z=402.50], EntityZombie['Zombie'/35982, l='MpServer', x=-220.50, y=63.00, z=537.21], EntitySkeleton['Skeleton'/35983, l='MpServer', x=-203.42, y=43.00, z=520.81], EntityPig['Pig'/143, l='MpServer', x=-265.50, y=70.00, z=538.66], EntitySkeleton['Skeleton'/35984, l='MpServer', x=-203.64, y=43.00, z=519.98], EntitySkeleton['Skeleton'/35985, l='MpServer', x=-205.65, y=43.00, z=516.65], EntitySkeleton['Skeleton'/35986, l='MpServer', x=-220.25, y=63.00, z=538.54], EntityPig['Pig'/153, l='MpServer', x=-275.28, y=68.00, z=533.59], EntityItem['item.item.egg'/10907, l='MpServer', x=-256.33, y=64.00, z=468.90], EntityPig['Pig'/158, l='MpServer', x=-205.53, y=69.00, z=455.69], EntitySkeleton['Skeleton'/30114, l='MpServer', x=-187.30, y=43.00, z=502.30], EntityPig['Pig'/162, l='MpServer', x=-175.56, y=68.00, z=426.27], EntityPig['Pig'/163, l='MpServer', x=-169.68, y=64.00, z=429.84], EntityCreeper['Creeper'/35491, l='MpServer', x=-196.50, y=20.00, z=398.50], EntityCreeper['Creeper'/35492, l='MpServer', x=-196.30, y=20.00, z=400.58], EntityCreeper['Creeper'/35493, l='MpServer', x=-197.46, y=22.00, z=402.17], EntityZombie['Zombie'/35750, l='MpServer', x=-211.50, y=32.00, z=411.50], EntityPig['Pig'/171, l='MpServer', x=-168.17, y=71.00, z=533.19], EntityBat['Bat'/35764, l='MpServer', x=-287.24, y=22.47, z=529.72], EntityBat['Bat'/35765, l='MpServer', x=-160.72, y=16.08, z=461.07], EntityBat['Bat'/35766, l='MpServer', x=-156.73, y=22.12, z=464.88], EntityBat['Bat'/35767, l='MpServer', x=-160.69, y=17.98, z=461.74], EntityBat['Bat'/35773, l='MpServer', x=-220.34, y=40.72, z=522.68], EntityPig['Pig'/191, l='MpServer', x=-157.75, y=67.00, z=508.25], EntityDamcell['Damcell'/35783, l='MpServer', x=-261.50, y=24.00, z=482.50], EntityZombieVillager['Zombie Villager'/35784, l='MpServer', x=-277.50, y=41.00, z=470.19], EntitySkeleton['Skeleton'/35529, l='MpServer', x=-260.50, y=53.00, z=409.50], EntitySpider['Spider'/35531, l='MpServer', x=-280.81, y=37.00, z=407.05], EntitySkeleton['Skeleton'/35787, l='MpServer', x=-253.50, y=61.00, z=388.50], EntityEnderman['Enderman'/35788, l='MpServer', x=-175.50, y=16.00, z=440.50], EntitySpider['Spider'/35532, l='MpServer', x=-298.50, y=47.00, z=458.50], EntityScarecrow['Scarecrow'/35533, l='MpServer', x=-282.11, y=36.00, z=405.67], EntitySkeleton['Skeleton'/35789, l='MpServer', x=-250.50, y=43.00, z=387.50], EntityZombie['Zombie'/35790, l='MpServer', x=-251.50, y=43.00, z=387.50], EntityRiftedEnderman['Rifted Enderman'/13777, l='MpServer', x=-225.30, y=45.00, z=444.59], EntitySkeleton['Skeleton'/35795, l='MpServer', x=-249.50, y=43.00, z=390.50], EntityPig['Pig'/212, l='MpServer', x=-154.50, y=70.00, z=465.75], EntityCreeper['Creeper'/35796, l='MpServer', x=-209.50, y=26.00, z=522.50], EntityPig['Pig'/213, l='MpServer', x=-159.22, y=69.00, z=470.48], EntityCreeper['Creeper'/35797, l='MpServer', x=-296.50, y=47.00, z=460.50], EntityRaven['Raven'/214, l='MpServer', x=-142.69, y=29.00, z=452.16], EntityArmorStand['Armor Stand'/215, l='MpServer', x=-141.50, y=63.00, z=451.50], EntityItemFrame['entity.ItemFrame.name'/216, l='MpServer', x=-141.97, y=68.50, z=454.50], EntityPig['Pig'/217, l='MpServer', x=-141.76, y=67.00, z=448.48], EntityItem['item.item.egg'/10980, l='MpServer', x=-244.15, y=73.00, z=444.33], EntityItem['item.item.egg'/35047, l='MpServer', x=-256.13, y=68.00, z=446.98], EntityRaven['Raven'/243, l='MpServer', x=-291.88, y=43.00, z=464.92], EntityZombie['Zombie'/35827, l='MpServer', x=-152.50, y=52.00, z=407.50], EntitySpider['Spider'/35829, l='MpServer', x=-288.50, y=44.00, z=399.50], EntityCreeper['Creeper'/32761, l='MpServer', x=-259.47, y=29.00, z=446.37], EntityBeetle['Beetle'/250, l='MpServer', x=-269.38, y=69.00, z=424.44], EntityWeta['Emperor Weta'/35322, l='MpServer', x=-146.42, y=24.00, z=513.94], EntityBonepile['Bonepile'/35836, l='MpServer', x=-207.50, y=24.00, z=423.50], EntityZombie['Zombie'/35838, l='MpServer', x=-286.50, y=32.00, z=395.50], EntityZombie['Zombie'/35327, l='MpServer', x=-223.50, y=18.00, z=422.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1967910352 bytes (1876 MB) / 3758096384 bytes (3584 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G6_pre1 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version       | Source                                      | Signature                                |
	|:------ |:--------------------- |:------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2        | minecraft.jar                               | None                                     |
	| LCHIJA | mcp                   | 9.42          | minecraft.jar                               | None                                     |
	| LCHIJA | FML                   | 8.0.99.99     | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860  | forge-1.12.2-14.23.5.2860.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core     | 1.12.2-1.0    | minecraft.jar                               | None                                     |
	| LCHIJA | xaeroworldmap_core    | 1.12.2-1.0    | minecraft.jar                               | None                                     |
	| LCHIJA | ancientbeasts         | 1.9.99999     | ancientbeasts-1.9.99999.jar                 | None                                     |
	| LCHIJA | baubles               | 1.5.2         | Baubles-1.12-1.5.2.jar                      | None                                     |
	| LCHIJA | bettercaves           | 1.12.2        | bettercaves-1.12.2-2.0.4.jar                | None                                     |
	| LCHIJA | bettermineshafts      | 1.12.2-2.2.1  | BetterMineshaftsForge-1.12.2-2.2.1.jar      | None                                     |
	| LCHIJA | mysticalmechanics     | 0.18          | Mystical+Mechanics-0.18.jar                 | None                                     |
	| LCHIJA | embers                | 1.19          | EmbersRekindled-1.19.jar                    | None                                     |
	| LCHIJA | mod_lavacow           | 1.3.3         | Fish's+Undead+Rising-1.3.3.jar              | None                                     |
	| LCHIJA | jei                   | 4.16.1.1001   | jei_1.12.2-4.16.1.1001.jar                  | None                                     |
	| LCHIJA | roots                 | @VERSION@     | Roots-1.12.2-3.1.7.jar                      | None                                     |
	| LCHIJA | mysticalworld         | 1.12.2-1.11.0 | mysticalworld-1.12.2-1.11.0.jar             | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6      | Patchouli-1.0-23.6.jar                      | None                                     |
	| LCHIJA | reachfix              | 1.0.8         | ReachFix-1.12.2-1.0.8.jar                   | None                                     |
	| LCHIJA | bettercombatmod       | 2.0.8         | RLCombat-1.12.2-2.0.8.jar                   | None                                     |
	| LCHIJA | soot                  | 1.10-hotfix   | Soot-1.10-hotfix.jar                        | None                                     |
	| LCHIJA | spartanshields        | 1.5.5         | SpartanShields-1.12.2-1.5.5.jar             | None                                     |
	| LCHIJA | spartanweaponry       | 1.5.3         | SpartanWeaponry-1.12.2-1.5.3.jar            | None                                     |
	| LCHIJA | spartanweaponryarcana | beta 1.0.3    | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar | None                                     |
	| LCHIJA | traverse              | 1.6.0         | Traverse-1.12.2-1.6.0-69.jar                | None                                     |
	| LCHIJA | treechop              | 0.14.6        | TreeChop-1.12.2-0.14.6.jar                  | None                                     |
	| LCHIJA | xaerominimap          | 23.3.3        | Xaeros_Minimap_23.3.3_Forge_1.12.jar        | None                                     |
	| LCHIJA | xaeroworldmap         | 1.29.5        | XaerosWorldMap_1.29.5_Forge_1.12.jar        | None                                     |
	| LCHIJA | thebetweenlands       | 3.9.6         | TheBetweenlands-3.9.6-universal.jar         | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | mysticallib           | 1.12.2-1.13.0 | mysticallib-1.12.2-1.13.0.jar               | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ReachFixPlugin (ReachFix-1.12.2-1.0.8.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_23.3.3_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.29.5_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 970/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/shamanism-resource-beta-v0-3.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 512.15
	OpenGlRenderer: NVIDIA GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by noobanidus** [comment] 2023-04-26 10:39
Is this new in 3.1.7? I'd hesitate to accuse Optifine of being responsible, although it is present. I'm not sure of what recent changes were in 3.1.7 but I know that the spell library was part of it.

**Comment by guide-for-you** [comment] 2023-04-26 10:44
Yeah its Roots 3.1.7

**Comment by guide-for-you** [comment] 2023-04-26 15:20
I deleted Optifine and problem still same

**Comment by SirMoogle** [comment] 2023-05-01 14:14
I'm encountering the same issue with 3.1.7 but I don't have Optifine installed. I've got the exact same error in my crash log. I didn't experience this in an earlier version, so I'm not sure if it has to do with incompatible assets between this one and a previous one.

**Comment by AdiLovee** [comment] 2023-05-04 16:37
> I'm not sure of what recent changes were in 3.1.7 but I know that the spell library was part of it

The changelog said "fixed inventory desync while or after spell library is opened". I also can confirm I'm getting the crash without optifine, and that downgrading to 3.1.6 removes the bug.

**Comment by Shibva** [comment] 2023-10-15 22:15
I can confirm this bug is still around

**Comment by Shibva** [comment] 2023-10-15 22:21
the bug might have something todo with the desync changes

**Comment by Shibva** [comment] 2023-10-15 22:24
OK I have made a breakthough
the crash appears to be provoked if you __Dont have the grammy in your active invetory__

if it's not in your inventory, any UI elements you interact with will cause the fatal error

if you do have it, it will function as intended. It should be noted the UI opens fully if you don't have a grammy, yet still shows the last grammy you have. 

It could be possible this is not intended
@ByThePowerOfScience

**Comment by guide-for-you** [comment] 2023-10-15 22:29
So,do I need to test it now to make sure that its problem in particular?

**Comment by Shibva** [comment] 2023-10-15 23:51
you can if you want

**Comment by guide-for-you** [comment] 2023-10-16 13:11
It seems that having Gramary in any inventory slots still cause crash,especially if you press "De-select"

**Comment by Shibva** [comment] 2023-10-16 15:22
That's.... not what is happening for me

The bug for me only happens if you DONT have one in your inventory

**Comment by guide-for-you** [comment] 2023-10-16 15:23
I tested with and without,in both cases I still get crash

**Comment by Shibva** [comment] 2023-10-18 05:33
its happening to me now as well it seems; this started when I got dandelion winds

Try going about in a new world and doing this stuff and test each one at a time

**Comment by ByThePowerOfScience** [comment] 2023-10-27 22:14
I didn't change anything related to this as far as I know, but there's probably something somewhere that's calling `SpellLibraryInfo#asList` multiple times per tick.  It tries to re-sort the list of spells while it's in the process of being sorted, causing the exception and crash.

It's not great that something is trying to get the list so often, but the good news is the fix _also_ stops that from being laggy at all!  It'll now just sort when the list is changed instead of every time we need to grab it.  Weird code, but easy fix.

I _highly_ highly recommend installing VanillaFix for its crash-handling so you don't have to restart the entire pack every time something somewhere has a dumb moment, but that's beside the point.

Fixed in commit.

**Closed as completed** 2023-10-28 18:33 UTC
Labels: bug
